name: challenge
channels:
  - conda-forge
  - defaults
dependencies:
  - bokeh~=2.3.2
  - holoviews~=1.14.4
  - hvplot~=0.7.2
  - datashader~=0.13.0
  - pandas~=1.2.4
  - xarray~=0.18.2
  - pillow~=8.2.0
  - jupyterlab~=3.0.16
  - scikit-learn~=0.24.2
